# Generated by Django 4.2.4 on 2023-09-18 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp', models.CharField(max_length=100)),
                ('es_correcto', models.BooleanField(default=False)),
                ('preg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pregunta')),
            ],
        ),
    ]
