# Generated by Django 4.2.5 on 2023-11-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatoapp', '0003_delete_profile_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
