# Generated by Django 4.2.5 on 2023-09-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testEnviroment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='pregunta_Usada',
            field=models.BooleanField(default=False),
        ),
    ]
